-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_chat_sessions (
  id integer NOT NULL,
  user_name character varying,
  session_id character varying NOT NULL,
  user_input text NOT NULL,
  ai_response text NOT NULL,
  interaction_number integer NOT NULL,
  scenario_name character varying DEFAULT 'TradeSphere_AI_Agent'::character varying,
  total_tokens integer,
  created_at timestamp with time zone DEFAULT now(),
  message_type character varying DEFAULT 'chat'::character varying,
  success boolean DEFAULT true,
  error_message text,
  interaction_summary text,
  customer_name character varying,
  customer_address text,
  customer_email character varying,
  customer_phone character varying,
  processing_time_ms numeric,
  ai_model character varying,
  prompt_tokens integer,
  completion_tokens integer,
  response_length integer,
  services_count integer,
  confidence_score numeric,
  gpt_splitting_time_ms numeric,
  parameter_collection_time_ms numeric,
  pricing_calculation_time_ms numeric,
  ai_generation_time_ms numeric,
  last_viewed_at timestamp with time zone,
  view_count integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  user_id uuid,
  customer_id uuid,
  customer_linked_at timestamp with time zone,
  customer_link_source character varying,
  CONSTRAINT ai_chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT vc_usage_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT VC Usage_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.crm_customers(id),
  CONSTRAINT fk_vc_usage_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ai_demo_messages (
  id bigint NOT NULL DEFAULT nextval('demo_messages_id_seq'::regclass),
  session_id text NOT NULL,
  message_text text NOT NULL,
  sender text NOT NULL,
  tech_id text,
  created_at timestamp with time zone DEFAULT now(),
  message_source character varying DEFAULT 'make_com'::character varying,
  company_id uuid,
  CONSTRAINT ai_demo_messages_pkey PRIMARY KEY (id),
  CONSTRAINT demo_messages_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.audit_customer_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  company_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  old_values jsonb,
  new_values jsonb,
  changed_by_user_id uuid,
  changed_at timestamp with time zone DEFAULT now(),
  ip_address inet,
  user_agent text,
  CONSTRAINT audit_customer_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  user_id text,
  action text NOT NULL,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.beta_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying UNIQUE,
  full_name character varying,
  job_title character varying,
  tech_uuid character varying NOT NULL UNIQUE,
  beta_code_used character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  first_name character varying,
  beta_code_id integer,
  is_admin boolean DEFAULT false,
  user_icon character varying NOT NULL DEFAULT 'User'::character varying,
  company_id uuid,
  CONSTRAINT beta_users_pkey PRIMARY KEY (id),
  CONSTRAINT beta_users_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.billing_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  amount numeric NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'succeeded'::character varying, 'failed'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  processed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  bank_account_name character varying,
  bank_account_last4 character varying,
  payment_type character varying DEFAULT 'monthly_subscription'::character varying CHECK (payment_type::text = ANY (ARRAY['monthly_subscription'::character varying, 'setup_fee'::character varying, 'addon'::character varying, 'refund'::character varying]::text[])),
  subscription_period_start date,
  subscription_period_end date,
  ach_status character varying,
  failure_code character varying,
  failure_message text,
  updated_at timestamp with time zone DEFAULT now(),
  stripe_payment_intent_id text,
  stripe_charge_id text,
  stripe_subscription_id text,
  stripe_invoice_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT billing_payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.billing_stripe_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setup_intent_id text NOT NULL UNIQUE,
  customer_id text NOT NULL,
  company_email text NOT NULL,
  company_name text NOT NULL,
  subscription_tier text,
  status text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_stripe_intents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_stripe_webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  company_id uuid,
  payment_id uuid,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_stripe_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhooks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT payment_webhooks_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.billing_payments(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id character varying NOT NULL DEFAULT generate_company_id() UNIQUE,
  name character varying NOT NULL,
  email character varying NOT NULL,
  website_url text,
  ai_personality character varying,
  color_theme jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  subscription_status character varying DEFAULT 'trial'::character varying CHECK (subscription_status::text = ANY (ARRAY['trial'::character varying, 'active'::character varying, 'past_due'::character varying, 'suspended'::character varying, 'cancelled'::character varying]::text[])),
  next_billing_date date,
  trial_end_date date DEFAULT (CURRENT_DATE + '14 days'::interval),
  monthly_amount numeric DEFAULT 2000.00,
  payment_method_status text DEFAULT 'pending'::text CHECK (payment_method_status = ANY (ARRAY['pending'::text, 'verified'::text, 'failed'::text, 'suspended'::text])),
  payment_method_verified_at timestamp with time zone,
  billing_email text,
  billing_name text,
  subscription_tier text DEFAULT 'standard'::text CHECK (subscription_tier = ANY (ARRAY['trial'::text, 'standard'::text, 'pro'::text, 'enterprise'::text])),
  subscription_started_at timestamp with time zone,
  billing_cycle_day integer DEFAULT 1 CHECK (billing_cycle_day >= 1 AND billing_cycle_day <= 28),
  last_payment_failed_at timestamp with time zone,
  payment_failure_count integer DEFAULT 0,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  onboarding_completed boolean DEFAULT false,
  ai_personality_config jsonb DEFAULT '{"tone": "professional", "formality": "balanced", "sales_approach": "consultative", "industry_language": "standard"}'::jsonb,
  branding_config jsonb DEFAULT '{"logo_url": null, "primary_color": "#3B82F6", "business_phone": null, "business_address": null}'::jsonb,
  onboarding_completed_at timestamp with time zone,
  owner_id uuid,
  cancellation_feedback text,
  stripe_customer_id text,
  stripe_payment_method_id text,
  stripe_setup_intent_id text,
  stripe_subscription_id text,
  timezone character varying DEFAULT 'America/Chicago'::character varying,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.company_notes (
  id bigint NOT NULL,
  notes_content text DEFAULT ''::text,
  updated_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_notes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_customer_conversation_summaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  session_id text NOT NULL,
  summary text,
  extracted_topics jsonb DEFAULT '[]'::jsonb,
  conversation_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_customer_conversation_summaries_pkey PRIMARY KEY (id),
  CONSTRAINT customer_conversation_summaries_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.crm_customers(id)
);
CREATE TABLE public.crm_customer_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  company_id uuid NOT NULL,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['created'::character varying, 'updated'::character varying, 'merged'::character varying, 'deleted'::character varying, 'stage_changed'::character varying, 'tag_added'::character varying, 'tag_removed'::character varying, 'note_added'::character varying]::text[])),
  event_data jsonb,
  created_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_customer_events_pkey PRIMARY KEY (id),
  CONSTRAINT customer_events_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.crm_customers(id),
  CONSTRAINT customer_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT customer_events_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.crm_customer_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  user_id text,
  feedback_type text NOT NULL CHECK (feedback_type = ANY (ARRAY['cancellation'::text, 'feature_request'::text, 'bug_report'::text, 'general'::text, 'support'::text])),
  reason text,
  feedback_text text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_customer_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT customer_feedback_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.crm_customer_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_name text NOT NULL,
  session_id text,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['view'::text, 'edit'::text, 'load'::text])),
  viewed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  user_id uuid,
  CONSTRAINT crm_customer_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_customer_interactions_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT customer_interactions_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.crm_customer_matching_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  key_type character varying NOT NULL CHECK (key_type::text = ANY (ARRAY['email'::character varying, 'phone'::character varying, 'name'::character varying]::text[])),
  key_value character varying NOT NULL,
  normalized_value character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_customer_matching_keys_pkey PRIMARY KEY (id),
  CONSTRAINT customer_matching_keys_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.crm_customers(id)
);
CREATE TABLE public.crm_customer_merge_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_customer_id uuid NOT NULL,
  target_customer_id uuid NOT NULL,
  merged_by_user_id uuid,
  merge_details jsonb,
  merged_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_customer_merge_log_pkey PRIMARY KEY (id),
  CONSTRAINT customer_merge_log_target_customer_id_fkey FOREIGN KEY (target_customer_id) REFERENCES public.crm_customers(id),
  CONSTRAINT customer_merge_log_merged_by_user_id_fkey FOREIGN KEY (merged_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.crm_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_name character varying NOT NULL,
  customer_email character varying,
  customer_phone character varying,
  customer_address text,
  customer_notes text,
  created_by_user_id uuid NOT NULL,
  created_by_user_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  merged_into_customer_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'merged'::character varying, 'deleted'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  lifecycle_stage character varying DEFAULT 'prospect'::character varying CHECK (lifecycle_stage::text = ANY (ARRAY['prospect'::character varying, 'lead'::character varying, 'customer'::character varying, 'churned'::character varying]::text[])),
  lifecycle_updated_at timestamp with time zone DEFAULT now(),
  tags ARRAY DEFAULT '{}'::text[],
  source character varying,
  source_campaign character varying,
  CONSTRAINT crm_customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT customers_merged_into_customer_id_fkey FOREIGN KEY (merged_into_customer_id) REFERENCES public.crm_customers(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  email text NOT NULL,
  role_type text NOT NULL CHECK (role_type = ANY (ARRAY['manager'::text, 'analyst'::text, 'sales'::text, 'field_tech'::text])),
  invited_by uuid NOT NULL,
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  used boolean NOT NULL DEFAULT false,
  used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.onboarding_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  used boolean NOT NULL DEFAULT false,
  used_at timestamp with time zone,
  created_ip_address text,
  created_user_agent text,
  used_ip_address text,
  used_user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT onboarding_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.ops_crew_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  crew_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'member'::crew_role,
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  is_active boolean DEFAULT true,
  certifications ARRAY DEFAULT '{}'::text[],
  skill_level integer DEFAULT 1 CHECK (skill_level >= 1 AND skill_level <= 5),
  availability_notes text,
  added_by_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_crew_members_pkey PRIMARY KEY (id),
  CONSTRAINT crew_members_crew_id_fkey FOREIGN KEY (crew_id) REFERENCES public.ops_crews(id),
  CONSTRAINT crew_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT crew_members_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ops_crews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  crew_name character varying NOT NULL,
  crew_code character varying,
  description text,
  crew_lead_user_id uuid,
  is_active boolean DEFAULT true,
  specializations ARRAY DEFAULT '{}'::text[],
  max_capacity integer DEFAULT 5 CHECK (max_capacity > 0 AND max_capacity <= 50),
  metadata jsonb DEFAULT '{}'::jsonb,
  color_code character varying,
  created_by_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_crews_pkey PRIMARY KEY (id),
  CONSTRAINT crews_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT crews_crew_lead_user_id_fkey FOREIGN KEY (crew_lead_user_id) REFERENCES public.users(id),
  CONSTRAINT crews_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ops_job_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  crew_id uuid NOT NULL,
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone NOT NULL,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::assignment_status,
  assignment_notes text,
  work_description text,
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  completion_notes text,
  estimated_hours numeric,
  actual_hours numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  assigned_by_user_id uuid NOT NULL,
  completed_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_job_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT job_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.ops_jobs(id),
  CONSTRAINT job_assignments_crew_id_fkey FOREIGN KEY (crew_id) REFERENCES public.ops_crews(id),
  CONSTRAINT job_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id),
  CONSTRAINT job_assignments_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ops_job_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  note_type character varying DEFAULT 'general'::character varying,
  subject character varying,
  content text NOT NULL,
  is_ai_generated boolean DEFAULT false,
  ai_confidence_score numeric CHECK (ai_confidence_score IS NULL OR ai_confidence_score >= 0::numeric AND ai_confidence_score <= 1::numeric),
  ai_model_version character varying,
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  is_internal boolean DEFAULT true,
  is_pinned boolean DEFAULT false,
  attachments jsonb DEFAULT '[]'::jsonb,
  related_service_ids ARRAY DEFAULT '{}'::uuid[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_job_notes_pkey PRIMARY KEY (id),
  CONSTRAINT job_notes_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.ops_jobs(id),
  CONSTRAINT job_notes_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ops_job_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  service_config_id uuid NOT NULL,
  service_name character varying NOT NULL,
  service_description text,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  total_price numeric NOT NULL CHECK (total_price >= 0::numeric),
  calculation_data jsonb DEFAULT '{}'::jsonb,
  pricing_variables jsonb DEFAULT '{}'::jsonb,
  notes text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  completed_by_user_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  added_by_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_job_services_pkey PRIMARY KEY (id),
  CONSTRAINT job_services_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.ops_jobs(id),
  CONSTRAINT job_services_service_config_id_fkey FOREIGN KEY (service_config_id) REFERENCES public.svc_pricing_configs(id),
  CONSTRAINT job_services_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT job_services_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ops_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  job_number character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'quote'::job_status,
  service_address text,
  service_city character varying,
  service_state character varying,
  service_zip character varying,
  service_location_notes text,
  requested_start_date date,
  scheduled_start_date date,
  scheduled_end_date date,
  actual_start_date timestamp with time zone,
  actual_end_date timestamp with time zone,
  estimated_total numeric,
  actual_total numeric,
  labor_cost numeric,
  material_cost numeric,
  quote_valid_until date,
  quote_sent_at timestamp with time zone,
  quote_approved_at timestamp with time zone,
  invoice_number character varying,
  invoiced_at timestamp with time zone,
  invoice_due_date date,
  paid_at timestamp with time zone,
  priority integer DEFAULT 0 CHECK (priority >= 0 AND priority <= 10),
  tags ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by_user_id uuid NOT NULL,
  updated_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ops_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.crm_customers(id),
  CONSTRAINT jobs_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT jobs_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.svc_material_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  service_config_id uuid NOT NULL,
  category_key text NOT NULL,
  category_label text NOT NULL,
  category_description text,
  sort_order integer DEFAULT 0,
  is_required boolean DEFAULT true,
  calculation_method text NOT NULL,
  default_depth_inches numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT svc_material_categories_pkey PRIMARY KEY (id),
  CONSTRAINT service_material_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT service_material_categories_service_config_id_fkey FOREIGN KEY (service_config_id) REFERENCES public.svc_pricing_configs(id)
);
CREATE TABLE public.svc_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  service_config_id uuid NOT NULL,
  material_name text NOT NULL,
  material_category text NOT NULL,
  material_description text,
  supplier_name text,
  image_url text,
  image_thumbnail_url text,
  unit_type text NOT NULL,
  price_per_unit numeric NOT NULL,
  units_per_package numeric,
  coverage_per_unit numeric,
  coverage_depth_inches numeric,
  length_inches numeric,
  width_inches numeric,
  thickness_inches numeric,
  weight_lbs numeric,
  waste_factor_percentage numeric DEFAULT 10.00,
  compaction_factor_percentage numeric DEFAULT 0.00,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  material_grade text,
  color text,
  finish text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT svc_materials_pkey PRIMARY KEY (id),
  CONSTRAINT service_materials_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT service_materials_service_config_id_fkey FOREIGN KEY (service_config_id) REFERENCES public.svc_pricing_configs(id),
  CONSTRAINT service_materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT service_materials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.svc_pricing_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  service_name character varying NOT NULL,
  hourly_labor_rate numeric NOT NULL DEFAULT 25.00,
  optimal_team_size integer NOT NULL DEFAULT 3,
  base_productivity numeric NOT NULL DEFAULT 50.00,
  base_material_cost numeric NOT NULL DEFAULT 5.84,
  profit_margin numeric NOT NULL DEFAULT 0.20,
  variables_config jsonb NOT NULL DEFAULT '{"formulaType": "two_tier", "categoryName": {"label": "Category Display Name", "description": "What this category controls", "variableName": {"type": "select", "label": "Variable Display Label", "default": "defaultOption", "options": {"defaultOption": {"label": "Default Option", "value": 0, "multiplier": 1.0}}, "effectType": "labor_time_percentage", "description": "How this affects the project", "calculationTier": 1}}, "formulaDescription": "Tier 1: Calculate labor hours | Tier 2: Calculate costs with complexity and profit", "serviceIntegrations": {"label": "Bundled Services", "description": "Automatically include related service calculations"}}'::jsonb,
  default_variables jsonb NOT NULL DEFAULT '{"categoryName": {"variableName": "defaultOption"}}'::jsonb,
  is_active boolean DEFAULT true,
  version character varying DEFAULT '2.0.0'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT svc_pricing_configs_pkey PRIMARY KEY (id),
  CONSTRAINT service_pricing_configs_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT service_pricing_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.system_feedback (
  id bigint NOT NULL DEFAULT nextval('feedback_id_seq'::regclass),
  user_name text NOT NULL,
  feedback_text text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_feedback_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT auth.uid(),
  company_id uuid NOT NULL,
  email character varying NOT NULL,
  role character varying NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_admin boolean DEFAULT false,
  user_icon character varying NOT NULL DEFAULT 'User'::character varying,
  name character varying NOT NULL DEFAULT 'User'::character varying,
  title character varying,
  is_developer boolean DEFAULT false,
  is_owner boolean DEFAULT false,
  is_manager boolean DEFAULT false,
  is_analyst boolean DEFAULT false,
  is_sales boolean DEFAULT false,
  is_field_tech boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);